spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6543/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 9090

logging:
  level:
    root: info


hash:
  cache:
    capacity: 100
    low-size-percentage: 20
  generation-batch:
    size: 40
  save-batch:
    size: 10
  get-batch:
    size: 30

task-executor:
  pool-size: 10
  queue-capacity: 20