spring:
  mvc:
    servlet:
      path: /api/v1  # Set default path for Spring

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      port: 6379
      host: localhost

  cache:
    type: redis

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

logging:
  level:
    root: info

encoder:
  base62:
    base: 62
    characters: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz

hashgenerator:
  batch-size: 1000

executor:
  threadpool-size: 5
  threadpool-queue-capacity: 100

cache:
  capacity: 500
  minPercent: 0.2

repository:
  hash:
    batchSizeSave: 500