spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        jdbc:
          batch_size: 256

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  redis:
    host: localhost
    port: 6379

server:
  port: 8080

logging:
  level:
    root: info

hash:
  unique-number-request-count: 200
  cache:
    size: 100
    percent: 20

executor:
  corePoolSize: 5
  maxPoolSize: 10
  queueCapacity: 100

scheduler:
  cleaning:
    url:
      cron: 0 0 0 * * *