spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  data:
    redis:
      port: 6379
      host: localhost
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  cache:
    type: redis

task:
  execution:
    pool:
      core-size: 5
      max-size: 10
    queue-capacity: 100

server:
  port: 8080

logging:
  level:
    root: info

hash:
  generator:
    batch-size: 100
  cache:
    low-threshold-percentage: 20
    queue:
      capacity: 90
  scheduled:
    cron : "0 0 0 * * *"

