spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

task-executor:
  thread-name-prefix: taskExecutor-
  queue-capacity: 100
  core-pool-size: 10
  max-pool-size: 20

hash:
  encoder:
    characterBase62: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
    hash-size: 6
  repository:
    batch-size: 1000
  generator:
    batch-size: 1000

server:
  port: 8080

logging:
  level:
    root: info