spring:
  mvc:
    servlet:
      path: /api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}

server:
  port: 8080

logging:
  level:
    root: info

batch:
  sublists: 10
  hashes: 10

thread-pool:
  size: 5
  queue: 10

static-url:
  url: https://sh.c/

cache:
  size: 100
  fill-threshold: 0.2

scheduler:
  cron: "0 0 0 * * *"