spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=url_shortener
    username: user
    password: password
  
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        jdbc:
          batch_size: 100

server:
  port: 8080

logging:
  level:
    root: info

repository:
  hashes:
    incoming-batch: 5

generator:
  uniqueNumbersRange: 50

encoder:
  base62Chars: "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  hash-length: 6

local-cache:
  minimalAmountInPercentage: 20
  maxSize: 5
  maxWaitTimeMillis: 5000

validator:
  hashPattern: "^[a-zA-Z0-9]{6}$"
  urlPattern: "\\b(https?|ftp|file):\\/\\/[-a-zA-Z0-9+&@#\\/%?=~_|!:,.;]*[-a-zA-Z0-9+&@#\\/%=~_|]"

async:
  core-pool-size: 4
  max-pool-size: 8
  queue-capacity: 500
  thread-name-prefix: "AsyncThread-"

redis:
  hostname: localhost
  port: 6379

scheduler:
  expired-time-years: 1
  cron:
    cleaner: "0 0 0 * * ?"