spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6543/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 10_000
        order_inserts: true
        generate_statistics: true

  data:
    redis:
      host: localhost
      port: 6379

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  profiles:
    active: jpa_profile

server:
  port: 8080
  base-url: http://localhost:8080/

logging:
  level:
    root: info

app:
  cleaner-scheduler:
    cron: 0 0 0 * * * # every day at 00:00:00
    period: P1Y # PnYnMnWnD format for Period.parse
  hash-generator:
    batch-size: 5000
    executor:
      pool-size: 1
      queue-size: 1
  hash-cache:
    cache-capacity: 1000
    fill-percent: 20
  redis-cache:
    hours-to-expire: 24