spring:
  data:
    redis:
      port: 6379
      host: localhost

  cache:
    type: redis

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    batch_size: 50

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

logging:
  level:
    root: info

generator:
  hash:
    count: 100

async:
  core-pool-size: 5
  max-pool-size: 50
  queue-capacity: 100