spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        order_inserts: true
        format_sql: true
        jdbc:
          batch_size: 5

server:
  port: 8087

logging:
  level:
    root: info

url-shortener-service:
  async:
    hash:
      maxPoolSize: 10
      corePoolSize: 25
      queueCapacity: 100
    cache:
      maxPoolSize: 10
      corePoolSize: 25
      queueCapacity: 100
  hashSize: 150
  base62: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
  batch-size: 100

