spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8088

app:
  protocol: http
  host: localhost

  hashes-generation:
    batch-size: 800
  hash-cache:
    size: 1000
    threshold: 200

thread-pool:
  fill-up-cache:
    size: 1
  hashes-generator:
    corePoolSize: 2
    maxPoolSize: 2
    queueCapacity: 2
    threadNamePrefix: "HashesGenerator-"

executor:
  thread-pool-size: 1

scheduler:
  clean-hashes:
    cron: "0 0 0 * * *" # every day