spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 9090

hash:
  batch:
    size: 100
  sequence:
    name: unique_number_seq
  thread-pool:
    size:
      min: 5
      max: 10
    keep-alive:
      time: 60
      time-unit: SECONDS
    queue:
      size: 10000

encoder:
  base:
    alphabet: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz

logging:
  level:
    root: info