spring:
  data:
    redis:
      port: 6379
      host: localhost
    cache:
      redis:
        time-to-live: 86400

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

logging:
  level:
    root: info

async:
  thread:
    pool:
      size: 5
    queue:
      capacity: 50

hash:
  range: 100
  scheduled:
    cron: "0 */10 * * * *"

  cache:
    size: 10
    threshold: 0.2

url:
  host: http://localhost:8080/urls