spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost

server:
  port: 8088

logging:
  level:
    root: info

hash:
  threadPool:
    initialPoolSize: 5
    maxPoolSize: 20
  queue:
    capacity: 200
  batchValues:
    saveBatch: 10_000
    getBatch: 10_000