spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  mvc:
    servlet:
      path: /api/v1

  data:
    redis:
      port: 6379
      host: localhost

server:
  port: 8080

logging:
  level:
    root: info

app:
  url-prefix: https://clck.com/

  scheduler:
    cleaner: "0 0 0 * * ?"
    period: 365 #Days - after what period to delete

  async:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 25
    thread_name_prefix: HashGenerator-

  hash:
    batch-size: 100
    cache:
      size: 10
      fill-percent: 20

  hash-generator:
    base: 62
    characters: "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
#    Additional formation options:
#    base: 58
#    characters: "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"
#    base: 16
#    characters: "0123456789ABCDEF"
#    base: 2
#    characters: "01"