spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=url_shortener
    username: user
    password: password

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        jdbc:
          batch_size: 100
        generate_statistics: true

server:
  port: 8080

logging:
  level:
    root: info

hashes:
  repository:
    hashes-batch: 1000