spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    root: info

hash:
  quantity-numbers:
    quantity: 150
  batch-size:
    size: 150

thread-pool:
  pool-size:
    hash-generator:
      max: 8
      core: 4
    scheduler:
      core: 2

cache:
  queue-size: 200
  fill-percent: 20

url-path:
  path: http://localhost:8080/api/v1/url/

scheduler:
  clean:
    cron: "0 0 * * * *"