spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: user
    password: password
  date:
    redis:
      port: 6379
      host: localhost
    ttl:
      hour:
        url: 24

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080
  servlet:
    context-path: /sh.com

logging:
  level:
    root: info

app:
  hash_generator:
    get_unique_number_size: 1_0
    max_db_hashes_size: 2_0
  hash_cache:
    hashes_max_size: 1_0
    hashes_min_size: 2
  async:
    hash_generator:
      core_pool_size: 10
      max_pool_size: 20
      queue_capacity: 1_000
      thread_name_prefix: HashGenerator-Async-
    hash_cache:
      core_pool_size: 10
      max_pool_size: 20
      queue_capacity: 1_000
      thread_name_prefix: HashCache-Async-
  scheduler:
    url_cleaner:
      cron: '0 0 0 * * *'
      url_lifetime_days: 365