spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  data:
    redis:
      host: localhost
      port: 6379
      ttl: 30
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  host: localhost
  port: 8080

logging:
  level:
    root: info

hash:
  batch-size: 50
  hash-size: 50
  unique-numbers-size: 300
  min-filling-percentage: 0.2
  cache-capacity: 300
scheduler:
  cron:
    cleaner: "0 0 0 * * ?"
    hash_generator: "0 0 0 * * ?"
task-executor:
  pool-size: 10
  queue-capacity: 20