spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 5
        order_inserts: true
        generate_statistics: true
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

logging:
  level:
    root: info

hash-generator:
  base62-alphabet: "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
  range: 100

async:
  generator-thread-pool:
    settings:
      core-pool-size: 4
      max-pool-size: 8
      queue-capacity: 100
  cache-thread-pool:
    settings:
      core-pool-size: 4
      max-pool-size: 8
      queue-capacity: 100