spring:
  datasource:
    service-name: urlShortenerService
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    amount-hash: 100

  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
      ttl: 10

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  base62:
    number of characters in hashcode: 6

  async:
    core pool size: 4
    max pool size: 10
    queue capacity: 50

server:
  port: 8080

logging:
  level:
    root: info