spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: user
    password: password
  date:
    redis:
      port: 6379
      host: localhost

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

logging:
  level:
    root: info

app:
  uri: 'http://localhost:8080/sh.com/'
  jdbc-template:
    batch-size:
      save-hashes: 500
  encoder:
    base_62:
      characters: 'AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz1032547698'
      base: 62
      hash_length: 6
  hash_generator:
    get_unique_number_size: 1_000
  hash_cache:
    hashes_max_size: 1_000
    hashes_min_size: 200
  async:
    hash_generator:
      core_pool_size: 10
      max_pool_size: 20
      queue_capacity: 1_000
      thread_name_prefix: HashGenerator-Async-
    hash_cache:
      core_pool_size: 10
      max_pool_size: 20
      queue_capacity: 1_000
      thread_name_prefix: HashCache-Async-
  scheduler:
    url_cleaner:
      cron: '0 0 0 * * *'
#      cron: '*/10 * * * * *'
      url_lifetime_days: 365