spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  redis:
    host: localhost
    port: 6379

server:
  port: 8080

logging:
  level:
    root: info

app:
  local_hash:
    capacity: 10000
    min: 100
  hash:
    cron: 0 0 0 * * *
    batch_size: 1000
    expiration: 1
  number_generator:
    batch_size: 1000
  async:
    corePoolSize: 5
    maxPoolSize: 10
    queueCapacity: 500
    threadNamePrefix: "AsyncExecutor-"
  scheduling:
    removal:
      cron: 0 */24 * * *
      months_before_expiration: 12