spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=url_shortener
    username: user
    password: password

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8091

logging:
  level:
    root: info

hash:
  unique-number:
    range: 100
  generation:
    scheduler:
      cron: " 0 */12 * * * " # every 12 hours
  cache:
    size: 10
    min-fill: 20 # percentage

async:
  generator-thread-pool:
    settings:
      core-pool-size: 4
      max-pool-size: 8
      queue-capacity: 100
  cache-thread-pool:
    settings:
      core-pool-size: 4
      max-pool-size: 8
      queue-capacity: 100