spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

hash:
  encoder:
    base62:
      value: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
  batch-size:
    get: 1000
    generate: 1000
  generator:
    async:
      core-pool-size: 10
      max-pool-size: 20
      queue-capacity: 50
      thread-name-prefix: HashGenerator-
  cache:
    size: 10
    low-threshold-percentage: 20
    async:
      core-pool-size: 5
      max-pool-size: 10
      queue-capacity: 50
      thread-name-prefix: CacheExecutor-

url:
  cleaner:
    cron: "0 0 0 * * *" # every day at midnight

logging:
  level:
    root: info