spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      port: 6379
      host: localhost

    batch_size: 5
    unique_numbers_number: 10

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

cache:
    type: redis

scheduler:
  cron:
    url_removal: 0 0 * * * ?

executor:
  threads_number: 10
  task_queue_size: 10000

hash:
  cache:
    size: 5
    min_threshold: 20
  length: 6

server:
  port: 8080

logging:
  level:
    root: info