spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
    hikari:
      data-source-properties:
        reWriteBatchedInserts: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      port: 6379
      host: localhost

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

logging:
  level:
    root: info

url:
  static-address: http://coolservice.com/
  hash:
    save-batch-size: 10
    get-batch-size: 5
    size: 6
    cache-size-percent: 20
    cache-size: 5
    pool:
      size: 10
      queue: 100
  cleaner:
    cron: "0 0 7 1 1 *"
