spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  host: localhost
  port: 8080

logging:
  level:
    root: info

hash:
  range: 100
  capacity: 500
  lowPercentage: 20

async:
  generator:
    poolSize: 2
    queueSize: 100

data:
  redis:
    port: 6379
    host: localhost
    url-ttl: 5

cleaner-scheduler:
  cron: "0 0 * * * *"

url:
  days-to-live: 5