spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: localhost
      port: 6379
      ttl:
        minutes: 1

  async:
    executor:
      corePoolSize: 10
      maxPoolSize: 20
      queueCapacity: 100

hash:
  batch_size: 1000
  cache:
    capacity: 100
    min_percentage_filling: 20

url:
  expiration:
    days: 365
    cleanup:
      cron: "@daily"

server:
  port: 8080

logging:
  level:
    root: info