spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 512
        order_inserts: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

logging:
  level:
    root: info

thread-pool:
  generator:
    core: 10
    max: 30
    queue: 50
  cache:
    core: 10
    max: 30
    queue: 50

hash-cache:
  minimum-percentage-to-add: 0.2
  size: 1500
