spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      cache:
        ttl-in-hours: 2

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

logging:
  level:
    root: info

encoder:
  base:
    characters: "abcdefghijklmnopqrsttuvwxyz0123456789ABCDEFDHIJKLMNOPQRSTUVWXYZ"
    divider: 62

hashGenerator:
  batch-size: 50

thread-pool-executor:
  core-pool-size: 5
  max-pool-size: 10
  queue-capacity: 150

schedulers:
  cleaner:
    old-url-period:
      days: 365
    cron: "0 0 * * * *" # every day at 00:00

cache:
  hash-cache:
    size: 100
    lowest-load-barrier: 20

app:
  url-prefix: https://